server:
    port: 8888

spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        # local db 연결
        # url : jdbc:mariadb://localhost:3306/encore?useUnicode=true
        # # 한글이 깨진다면 useUnicode
        # username : root
        # password : 12345Q

        # cloud db 연결 : port가 달라진다.
        url : jdbc:mariadb://localhost:6033/encore?useUnicode=true 
        username : work_user
        password : work_passwd

mybatis:
    mapper-locations: mappers/*.xml

