name : Java with Gradle

on : 
  push :
    branches : [main]
    
jobs :
  build :
    runs-on:  ubuntu-latest
      # runner 설치 (os)

    steps :
    - name : Source Checkout
      uses : actions/checkout@v2
      