name : Java with Gradle

on : 
  push :
    branches : [main]
    
jobs :
  build :
    runs-on:  ubuntu-latest
      # runner 설치 (os)

    steps :
    - name : Source Checkout
      uses : actions/checkout@v2
      # runner에 소스코드 설치

    - name : Setup JDK 17
      uses : actions/setup-java@v2
      with : 
        java-version : '17'
        distribution : 'adopt'
      # JAVA 버전 설정